language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script:
  - cd browser
  - npm install
  - npm run lint
  - npm test
  - cd ..
  - cd nodejs
  - npm install
  - npm run lint
  - npm test
  - cd ..
